version: '3.8'

services:
  postgres-restaurant:
    image: postgres:16
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-restaurant-data:/var/lib/postgresql/data
    networks:
      - restaurant-net
    restart: unless-stopped

  backend-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-restaurant
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-restaurant:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres-restaurant
    networks:
      - restaurant-net
    restart: unless-stopped

volumes:
  postgres-restaurant-data:

networks:
  restaurant-net:
