services:
  postgres-restaurant:
    image: postgres:16
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-restaurant-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-restaurant-data:
