spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_POOL_MIN:5}
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate # Jamais create/update en prod !
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.orderly.votybe: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/orderly/application.log

orderly:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  security:
    rate-limit:
      requests-per-window: ${RATE_LIMIT_REQUESTS:1000}
